# JPA
spring:
  jpa:
  properties:
  hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  ddl-auto: update
  # MySql
  datasource:
    url: jdbc:mysql://localhost:3306/kanbanlabdb
    username: root
    password: root
  # Connection Pool
  hikari:
    connection-timeout: 20000
    minimum-idle: 10
    maximum-pool-size: 10
    idle-timeout: 10000
    max-lifetime: 1000
    auto-commit: true
  # Mail Service
  mail:
    host: smtp.gmail.com
    port: 587
    username: kanbanlabb@gmail.com
    password: zqmmspygebhrhphq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#spring.datasource.url=jdbc:mysql://localhost:3306/kanbanlabdb
#spring.datasource.username=root
#spring.datasource.password=root
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=kanbanlabb@gmail.com
#spring.mail.password=zqmmspygebhrhphq
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true




